# Professor example discussed in class----

In [47]:
import pandas as pd

data = {'A': [1,3,5],
        'B': [2,4,6]
        }

df = pd.DataFrame(data,columns=['A','B'])

covMatrix = pd.DataFrame.cov(df)
print (covMatrix)

     A    B
A  4.0  4.0
B  4.0  4.0


# Using Github Example

https://github.com/gskdhiman/Understanding-PCA/blob/master/PCA_code.ipynb

https://medium.com/analytics-vidhya/understanding-principle-component-analysis-pca-step-by-step-e7a4bb4031d9

In [34]:

import numpy as np
import pandas as pd

In [54]:

A = np.matrix([[1,2],[3,4],[5,6]])

df = pd.DataFrame(A,columns  = ['f1','f2'])
df

f1  f2
0   1   2
1   3   4
2   5   6

In [55]:

df_std  = (df - df.mean()) / (df.std())
df_std

f1   f2
0 -1.0 -1.0
1  0.0  0.0
2  1.0  1.0

In [56]:
df_cov = np.cov(df_std.T, bias = 1)
df_cov

array([[0.66666667, 0.66666667],
       [0.66666667, 0.66666667]])

In [57]:
cov_mat = np.cov(df_std.T, bias = 0)
cov_mat

array([[1., 1.],
       [1., 1.]])

In [58]:
eigen_val, eigen_vectors = np.linalg.eig(cov_mat)

In [59]:
print(eigen_val)

[2. 0.]


In [60]:
print(eigen_vectors)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [68]:
n_components=2

In [69]:
top_eigen_vectors = eigen_vectors[:,:n_components]

In [70]:
top_eigen_vectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [71]:
top_eigen_vectors.shape

(2, 2)

In [72]:
np.array(df_std).shape

(3, 2)

In [73]:
transformed_data = np.matmul(np.array(df_std),top_eigen_vectors)

In [74]:
pd.DataFrame(data = transformed_data
             , columns = ['principal component '+ str(i+1) for i in range(n_components)])

principal component 1  principal component 2
0              -1.414214                    0.0
1               0.000000                    0.0
2               1.414214                    0.0

In [75]:
transformed_data.shape

(3, 2)

In [76]:
from sklearn.decomposition import PCA
pca = PCA(n_components=n_components)
principalComponents = pca.fit_transform(df_std)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component '+ str(i+1) for i in range(n_components)])

In [77]:
principalDf

principal component 1  principal component 2
0              -1.414214           2.372134e-17
1               0.000000           0.000000e+00
2               1.414214           2.372134e-17