# Finding out eigen values and eigen vectors of a given matrix

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la


consider a matrix

In [ ]:
# #x = np.array([[2],
#               [1]])

# A = np.array([[2, 1,0],
#               [0,2,0],
#              [0,0,2]])

A = np.array([[2, -12],
              [1, -5]])


A

function la.eig returns  a tuple ( eigenvals,eigenvecs) where eigvals is a 1D numpy array of giving eigenvalues of A, and eigvecs is a 2D Numpy array with corresponding eigenvectors in the columns.

In [ ]:
results = la.eig(A)
results

The eigenvalues of A are:

In [ ]:
print(results[0])

So the eigen values are : 2 , 2, 2

The corresponding eigen vectors are:

In [ ]:
print(results[1])

Unpacking the tuple:

In [ ]:
eigvals, eigvecs = la.eig(A)
print(eigvals)

In [ ]:
print(eigvecs)

In [ ]:
# converting array of eigen values to real numbers

eigvals = eigvals.real
print(eigvals)

In [ ]:
# position of an eigen value in the array eigvals correspond to the column in eigvecs with its eigenvectors

lambda1 = eigvals[1]
print(lambda1)

# To check if a vector is eigen vector of a corresponding another vector

In [ ]:
import numpy as np

a = np.array([[2,-4], [3,-6]])
w, v = np.linalg.eig(a)

print('eigen values: ' ,w,'\n')     
print('eigen vectors: \n\n' ,v)



------------------------------------------------------------------------------------------------------
So, the eigenvalue

w[0] goes with v[:,0]
w[1] goes with v[:,1]
We will now check if the condition

A
v
=
λ
v


holds here.

The LHS of the above equation 
A
v
 here is

In [ ]:
np.dot(a,v[:,0])

and the RHS part 
λ
v
 is

In [ ]:
np.dot(w[0],v[:,0])

In [ ]:
# So if the returned eigenvalues and eigenvectors are correct, the following line of script should return True

print(np.allclose(np.dot(a,v[:,0]),np.dot(w[0],v[:,0])))

In [ ]:
# Also, just to see if the returned eigenvectors are normalized, use the numpy.linalg.norm() 
# function to cross-check them. The below script should return 1.0 in both the print() statements.

print(np.linalg.norm(v[:,0]))
print(np.linalg.norm(v[:,1]))

# PCA Algorithm

In [20]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig


# define a matrix
A = array([[1,1,9], [2, 4,6], [3,7,4], [4,11,4],[5,9,2]])
print(A)


[[ 1  1  9]
 [ 2  4  6]
 [ 3  7  4]
 [ 4 11  4]
 [ 5  9  2]]


In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig


# define a matrix
A = array([[4,1], [2,3], [5,4], [1,0]])
print(A)

[[4 1]
 [2 3]
 [5 4]
 [1 0]]


In [16]:
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)

[3.  6.4 5. ]


In [21]:
# center columns by subtracting column means
C = A - M
print(C)

[[-2.  -5.4  4. ]
 [-1.  -2.4  1. ]
 [ 0.   0.6 -1. ]
 [ 1.   4.6 -1. ]
 [ 2.   2.6 -3. ]]


In [22]:
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)


[[ 2.5   5.75 -4.  ]
 [ 5.75 15.8  -9.25]
 [-4.   -9.25  7.  ]]


In [23]:
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print('eigen vectors = ' , vectors, '\n')
print('eigen values = ' , values)

eigen vectors =  [[ 0.31047214  0.91384283 -0.26172187]
 [ 0.80139329 -0.10354986  0.58910629]
 [-0.5112493   0.39264324  0.76449686]] 

eigen values =  [23.92868148  0.12980618  1.24151234]


In [24]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[-6.99346524  0.30205652  0.40025719]
 [-2.74506534 -0.27267994 -0.38763637]
 [ 0.99208527 -0.45477315 -0.41103308]
 [ 4.50813057  0.04487025  1.68367021]
 [ 4.23831473  0.38052632 -1.28525795]]


# To find projected matrix

We can calculate a Principal Component Analysis on a dataset using the PCA() class in the scikit-learn library. The benefit of this approach is that once the projection is calculated, it can be applied to new data again and again quite easily.

When creating the class, the number of components can be specified as a parameter.

The class is first fit on a dataset by calling the fit() function, and then the original dataset or other data can be projected into a subspace with the chosen number of dimensions by calling the transform() function.

Once fit, the eigenvalues and principal components can be accessed on the PCA class via the explained_variance_ and components_ attributes.

The example below demonstrates using this class by first creating an instance, fitting it on a 3×2 matrix, accessing the values and vectors of the projection, and transforming the original data.



In [13]:
# Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[4, 1], [2, 3], [5, 4], [1, 0]])
print(A)
print()

# create the PCA instance
pca = PCA()
print()

# fit on data
pca.fit(A)
print()

# access values and vectors
print('Principal components:')
print(pca.components_)
print()
print('values:')
print(pca.explained_variance_)
print()

# transform data
print('transformed data:')
B = pca.transform(A)
print(B)

[[4 1]
 [2 3]
 [5 4]
 [1 0]]



Principal components:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

values:
[5.33333333 1.33333333]

transformed data:
[[ 1.11022302e-16  1.41421356e+00]
 [-1.11022302e-16 -1.41421356e+00]
 [ 2.82842712e+00 -2.22044605e-16]
 [-2.82842712e+00  2.22044605e-16]]


Running the example first prints the 3×2 data matrix, then the principal components and values, followed by the projection of the original matrix.

We can see, that with some very minor floating point rounding that we achieve the same principal components, singular values, and projection as in the previous example.