In [38]:
import sys, json, numpy as np

What is a stochastic matrix? It is a matrix in which either all the entries of each row or column add up to 1. In this case, the entries of each column add up to 1, so this matrix is column-stochastic. This type of matrix represents a probability distribution, in which each matrix[i][j] represents the probability that a web surfer who is currently on page j will visit page i.

In [39]:
def create_stochastic(adj_list):
  n = len(adj_list)
  matrix = np.zeros((n, n))
  for col, line in enumerate(adj_list):
    if len(line) > 0:
      for index in line:
        matrix[index][col] = 1/(len(line))
    else:
      for index in range(n):
        matrix[index][col] = 1/n
  return matrix

In [40]:
adj_list = [[2,1],[2],[0],[]]
stoch_matrix = create_stochastic(adj_list)


In [41]:
stoch_matrix

array([[0.  , 0.  , 1.  , 0.25],
       [0.5 , 0.  , 0.  , 0.25],
       [0.5 , 1.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.25]])

In [30]:
def create_transitional(stoch_matrix):
  n = len(stoch_matrix)
  d = 0.85 #damping factor
  E = np.ones((n, n)) #create matrix of 1's
  part1 = np.multiply(((1-d)/n), E)
  part2 = np.multiply(d, stoch_matrix)
  transition_matrix = np.add(part1, part2)
  print(transition_matrix)
  print('\n')
  return transition_matrix

In [31]:
transition_matrix = create_transitional(stoch_matrix)

[[0.0375 0.0375 0.8875 0.25  ]
 [0.4625 0.0375 0.0375 0.25  ]
 [0.4625 0.8875 0.0375 0.25  ]
 [0.0375 0.0375 0.0375 0.25  ]]




In [35]:
#----------------------------------------------------------------------------
  

In [44]:
#For r = 0.8Mr + c

import numpy

def create_transitional(stoch_matrix):
  n = len(stoch_matrix)
  d = 0.8 #damping factor
  matrix = [(0.2),(0.2),(0.2),(0.2)]
  E = numpy.transpose(matrix)
  part1 = np.multiply(((1-d)/n), E)
  part2 = np.multiply(d, stoch_matrix)
  transition_matrix = np.add(part1, part2)
  print(transition_matrix)
  print('\n')
  return transition_matrix

In [45]:
transition_matrix = create_transitional(stoch_matrix)

[[0.01 0.01 0.81 0.21]
 [0.41 0.01 0.01 0.21]
 [0.41 0.81 0.01 0.21]
 [0.01 0.01 0.01 0.21]]




In [ ]:
#------------------------------------------------------------------------

In [46]:
def within_err_bound(v1, v2, err_bound):
  diff_vector = np.subtract(v2, v1)
  for diff in diff_vector:
    if abs(diff) > err_bound:
      return False
  return True

In [47]:
def calculate_pagerank(transition_matrix):
  n = len(transition_matrix)
  err_bound = 0.005
  v1 = np.full((n, 1), 1/n)
  v2 = np.matmul(transition_matrix, v1)
  count = 1
  print(v2)
  print('\n')
  while not within_err_bound(v1, v2, err_bound): 
    #keep iterating multiplication until difference between v1 and v2 for all entries is under err bound
    v1 = v2
    v2 = np.matmul(transition_matrix, v1)
    count += 1
    print(v2)
    print('\n')
  print('iteration:', count)  
  return {'vector': v2.tolist(), 'iterations': count}

In [48]:
result = calculate_pagerank(transition_matrix)

[[0.26]
 [0.16]
 [0.36]
 [0.06]]


[[0.3084]
 [0.1244]
 [0.2524]
 [0.0204]]


[[0.213056]
 [0.134496]
 [0.234016]
 [0.011136]]


[[0.19536704]
 [0.09337664]
 [0.20097344]
 [0.00815424]]


[[0.16738831]
 [0.08475638]
 [0.15945769]
 [0.00660956]]


[[0.13307018]
 [0.07245936]
 [0.14026446]
 [0.00550403]]


[[0.11682535]
 [0.05784186]
 [0.11580935]
 [0.00461379]]


[[0.09652114]
 [0.0506038 ]
 [0.09687729]
 [0.00387366]]


[[0.08075532]
 [0.04186195]
 [0.08234499]
 [0.00325349]]


[[0.06860885]
 [0.03503499]
 [0.06852454]
 [0.00273286]]


[[0.05711522]
 [0.02973912]
 [0.05776711]
 [0.00229558]]


[[0.04814197]
 [0.02477437]
 [0.04856567]
 [0.00192829]]


[[0.0404723 ]
 [0.02087655]
 [0.04069605]
 [0.00161976]]


[[0.03391744]
 [0.01754952]
 [0.03425076]
 [0.0013606 ]]


[[0.02854351]
 [0.01470988]
 [0.02874949]
 [0.0011429 ]]


[[0.02395963]
 [0.01237744]
 [0.02414534]
 [0.00096004]]


iteration: 16


  You can see the part of the console output for this example here. Even in the first few iterations, you can see the values changing by a smaller amount each time. This particular example takes 8 iterations until the differences fall below the error bound. The last vector output in this iterative process is the final pagerank. 
  
  
  
  Given this vector, we can see that Page C has the highest rank. This is expected because Page C has the most inbound links of any page. But notice that Page A has a very high rank, too, despite having only one inbound link! This is because this single inbound link comes from Page C, which happens to be the most important page. 